### ISSUE TITLE
Race-Condition

### ISSUE THREAD

**Issue by nuuk42** [smitchell556/cuttlepool#36]
The class CuttlePool has a race-condition in its method get_resource.

Setup: 

- the pool contains one available resource
- no resources are in use
- two threads are using the pool

Sequence of events:

1. thread-1:: calls "get_resource"
2. thread-1:: the method "_get()" returns the object "_ResourceTracker-1" and move this
              object to the part of the "_reference_queue" that contains the resources that
              are in use. 
3. thread-1:: calls "self.ping" using the resource from "_ResourceTracker-1" as argument.
              Note: at this point in time a call to the method "available()" of the object
              "_ResourceTracker-1" returns "True" because the "weakref" to the wraped resource
              has not yet been established. This happens later in "get_resource" with a call to
              the method "wrap_resource".
4. thread-2:: calls "get_resource" 
5. thread-2:: The pool's "empty()" return "True" and so "_harvest_lost_resources" is called to look
              for resources that haven been properly returned to pool.
6. thread-2:: "_harvest_lost_resources" loops the part of the "_reference_queue" that contains the 
              "_ResourceTracker" objects of resources that are in use. It finds "_ResourceTracker-1"
              and calls the "available" method which returns "True". 
              The method "_harvest_lost_resources" then returns the object "_ResourceTracker-1" to the 
              part of the "_reference_queue" that contains the available resources.
7. thread-2:: The method "_get()" returns "_ResourceTracker-1"

As a result, boths thread are using the same resource.

**Comment by smitchell556** [comment]
Yup, that’s a race condition. Thanks for finding that bugger. I can wrap get_resource with the lock which should solve the problem. I’ll have this fixed today.

**Comment by smitchell556** [comment]
Resolved in PR #37.

**Comment by nuuk42** [comment]
Hallo Spencer,
putting a lock onto the entier "get_resource" would surly fix this - but...: the "ping" function of the resource may take some time - specially if the resource it "down". I tried something else to fix this: let the "_get()" method return the "ResourceTracker" and the wraped resource. I'll append the modified version - it contains a lot of traces...
Best regards,Nuuk.


    On Monday, December 2, 2019, 3:36:00 PM GMT+1, Spencer Mitchell <notifications@github.com> wrote:  
 
 
Closed #36.

**Comment by smitchell556** [comment]
Yes, I think you're right. The lock is really meant to be used to prevent race conditions when accessing the queue, not individual resources. `_get` and `_make_resource` should return the wrapped resource as opposed to the tracker.

**Comment by nuuk42** [comment]
(..sorry for answering late -  I'd some days "off"...)
The problem with the function "get_resource" as you have it in the version 0.9 is the call to "ping()":

      def get_resource(self, resource_wrapper=None):
        ...
        with self._lock:
            ...
            # Ensure resource is active.
            if not self.ping(rtracker.resource):
               ...

So, the pool it locked until the function ping() returns which may take a long time if - for example - one  node of the Resource-Cluster is down. Think of a case where 10 free resources are in the pool, 11 client threads did call "get_resource()" and  "ping()" has 30s timeout until it notices that the resource has moved to an other host. The last client call would have to wait for 300s (!) until it gets
[cuttlepool.zip](https://github.com/smitchell556/cuttlepool/files/3992450/cuttlepool.zip)

 a fesh resource....

I suggest the following:

1. Change the function "_get()" to return both, the _ResourceTracker object and the wrapped resource:

       def _get(self, timeout, resource_wrapper_class):
           with self_lock:
               ...
               return rtracker, rtracker.wrap_resource(self, resource_wrapper_class)

2. Change the function "_make_resource()" to return both, the_ResourceTracker object and the wrapped resource:

       def _make_resource(self, resource_wrapper_class):
           with self_lock:
               ...
               return rtracker, rtracker.wrap_resource(self, resource_wrapper_class)

3. Change the function "get_resource()" so that "_ResourceTracker" and the wrapped resource are stored when calling "_get()" or "_make_resource()". Example:



        try:
            # try the get a resource from the pool. Do not wait; pool is empty at very first call
            rtracker, wrapedResource = self._get(0, resource_wrapper)
        except PoolEmptyError:
            pass

  
3. Remove the statement `with self._lock:` at line 300 in the function "get_resource()" - this is not needed anymore.

**Comment by smitchell556** [comment]
Overall, this looks good. I think if the wrapped resource is being returned by `_make_resource` and `_get`, then the `rtracker` doesn't need to be returned as well. Can you make a pull request with these changes?
